// Generated from: feature\checkout-edge-cases.feature
import { test } from "../../fixtures/fixture";

test.describe('Cart and Checkout Edge Cases and Negative Scenarios', () => {

  test.beforeEach('Background', async ({ Given, loginPage, page }, testInfo) => { if (testInfo.error) return;
    await Given('I am on home page', null, { page }); 
    await Given('I Login as "valid"', null, { loginPage }); 
  });
  
  test('Verify cart persists after page refresh', async ({ Given, When, Then, And, inventoryPage, inventoryState, page }) => { 
    await Given('I see page containing "Products"', null, { inventoryPage }); 
    await When('I choose random item and add it to cart', null, { inventoryPage, inventoryState }); 
    await And('I refresh the page', null, { page }); 
    await Then('I verify cart item persists', null, { inventoryPage }); 
  });

  test('Checkout with only first name', async ({ Given, When, Then, And, cartPage, checkoutPage, inventoryPage, inventoryState }) => { 
    await Given('I see page containing "Products"', null, { inventoryPage }); 
    await When('I choose random item and add it to cart', null, { inventoryPage, inventoryState }); 
    await And('I open cart and verify the added item', null, { cartPage, inventoryPage, inventoryState }); 
    await And('I proceed to checkout', null, { cartPage }); 
    await When('I fill checkout with only first name "John"', null, { checkoutPage }); 
    await Then('I see error message "Error: Last Name is required"', null, { checkoutPage }); 
  });

  test('Checkout with only last name', async ({ Given, When, Then, And, cartPage, checkoutPage, inventoryPage, inventoryState }) => { 
    await Given('I see page containing "Products"', null, { inventoryPage }); 
    await When('I choose random item and add it to cart', null, { inventoryPage, inventoryState }); 
    await And('I open cart and verify the added item', null, { cartPage, inventoryPage, inventoryState }); 
    await And('I proceed to checkout', null, { cartPage }); 
    await When('I fill checkout with only last name "Doe"', null, { checkoutPage }); 
    await Then('I see error message "Error: First Name is required"', null, { checkoutPage }); 
  });

  test('Checkout with only zip code', async ({ Given, When, Then, And, cartPage, checkoutPage, inventoryPage, inventoryState }) => { 
    await Given('I see page containing "Products"', null, { inventoryPage }); 
    await When('I choose random item and add it to cart', null, { inventoryPage, inventoryState }); 
    await And('I open cart and verify the added item', null, { cartPage, inventoryPage, inventoryState }); 
    await And('I proceed to checkout', null, { cartPage }); 
    await When('I fill checkout with only zip code "12345"', null, { checkoutPage }); 
    await Then('I see error message "Error: First Name is required"', null, { checkoutPage }); 
  });

  test('Verify checkout total calculation accuracy', async ({ Given, When, Then, And, cartPage, checkoutPage, inventoryPage }) => { 
    await Given('I see page containing "Products"', null, { inventoryPage }); 
    await When('I add item at index 0 to cart', null, { inventoryPage }); 
    await And('I add item at index 1 to cart', null, { inventoryPage }); 
    await And('I open cart and verify both items', null, { cartPage, inventoryPage }); 
    await And('I proceed to checkout', null, { cartPage }); 
    await And('I fill checkout information with "Jane" "Smith" "67890"', null, { checkoutPage }); 
    await Then('I verify the total calculation is correct', null, { checkoutPage }); 
  });

  test('Verify checkout flow before completion', async ({ Given, When, Then, And, cartPage, checkoutPage, inventoryPage, inventoryState }) => { 
    await Given('I see page containing "Products"', null, { inventoryPage }); 
    await When('I choose random item and add it to cart', null, { inventoryPage, inventoryState }); 
    await And('I open cart and verify the added item', null, { cartPage, inventoryPage, inventoryState }); 
    await And('I proceed to checkout', null, { cartPage }); 
    await And('I fill checkout information with "Test" "User" "12345"', null, { checkoutPage }); 
    await Then('I verify checkout overview and totals', null, { checkoutPage }); 
  });

  test('Verify cart badge updates correctly', async ({ Given, When, Then, And, cartPage, inventoryPage, inventoryState }) => { 
    await Given('I see page containing "Products"', null, { inventoryPage }); 
    await When('I choose random item and add it to cart', null, { inventoryPage, inventoryState }); 
    await Then('I verify cart badge shows 1', null, { inventoryPage }); 
    await When('I choose random item and add it to cart', null, { inventoryPage, inventoryState }); 
    await Then('I verify cart badge shows 2', null, { inventoryPage }); 
    await When('I open cart and verify both items', null, { cartPage, inventoryPage }); 
    await And('I remove all items from cart', null, { cartPage }); 
    await Then('I verify cart badge is not visible', null, { inventoryPage }); 
  });

});

// == technical section ==

test.use({
  $test: [({}, use) => use(test), { scope: 'test', box: true }],
  $uri: [({}, use) => use('feature\\checkout-edge-cases.feature'), { scope: 'test', box: true }],
  $bddFileData: [({}, use) => use(bddFileData), { scope: "test", box: true }],
});

const bddFileData = [ // bdd-data-start
  {"pwTestLine":11,"pickleLine":7,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given I am on home page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given I Login as \"valid\"","isBg":true,"stepMatchArguments":[{"group":{"start":11,"value":"\"valid\"","children":[{"start":12,"value":"valid","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":12,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"Given I see page containing \"Products\"","stepMatchArguments":[{"group":{"start":22,"value":"\"Products\"","children":[{"start":23,"value":"Products","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":13,"gherkinStepLine":9,"keywordType":"Action","textWithKeyword":"When I choose random item and add it to cart","stepMatchArguments":[]},{"pwStepLine":14,"gherkinStepLine":10,"keywordType":"Action","textWithKeyword":"And I refresh the page","stepMatchArguments":[]},{"pwStepLine":15,"gherkinStepLine":11,"keywordType":"Outcome","textWithKeyword":"Then I verify cart item persists","stepMatchArguments":[]}]},
  {"pwTestLine":18,"pickleLine":13,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given I am on home page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given I Login as \"valid\"","isBg":true,"stepMatchArguments":[{"group":{"start":11,"value":"\"valid\"","children":[{"start":12,"value":"valid","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":19,"gherkinStepLine":14,"keywordType":"Context","textWithKeyword":"Given I see page containing \"Products\"","stepMatchArguments":[{"group":{"start":22,"value":"\"Products\"","children":[{"start":23,"value":"Products","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":20,"gherkinStepLine":15,"keywordType":"Action","textWithKeyword":"When I choose random item and add it to cart","stepMatchArguments":[]},{"pwStepLine":21,"gherkinStepLine":16,"keywordType":"Action","textWithKeyword":"And I open cart and verify the added item","stepMatchArguments":[]},{"pwStepLine":22,"gherkinStepLine":17,"keywordType":"Action","textWithKeyword":"And I proceed to checkout","stepMatchArguments":[]},{"pwStepLine":23,"gherkinStepLine":18,"keywordType":"Action","textWithKeyword":"When I fill checkout with only first name \"John\"","stepMatchArguments":[{"group":{"start":37,"value":"\"John\"","children":[{"start":38,"value":"John","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":24,"gherkinStepLine":19,"keywordType":"Outcome","textWithKeyword":"Then I see error message \"Error: Last Name is required\"","stepMatchArguments":[{"group":{"start":20,"value":"\"Error: Last Name is required\"","children":[{"start":21,"value":"Error: Last Name is required","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":27,"pickleLine":21,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given I am on home page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given I Login as \"valid\"","isBg":true,"stepMatchArguments":[{"group":{"start":11,"value":"\"valid\"","children":[{"start":12,"value":"valid","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":28,"gherkinStepLine":22,"keywordType":"Context","textWithKeyword":"Given I see page containing \"Products\"","stepMatchArguments":[{"group":{"start":22,"value":"\"Products\"","children":[{"start":23,"value":"Products","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":29,"gherkinStepLine":23,"keywordType":"Action","textWithKeyword":"When I choose random item and add it to cart","stepMatchArguments":[]},{"pwStepLine":30,"gherkinStepLine":24,"keywordType":"Action","textWithKeyword":"And I open cart and verify the added item","stepMatchArguments":[]},{"pwStepLine":31,"gherkinStepLine":25,"keywordType":"Action","textWithKeyword":"And I proceed to checkout","stepMatchArguments":[]},{"pwStepLine":32,"gherkinStepLine":26,"keywordType":"Action","textWithKeyword":"When I fill checkout with only last name \"Doe\"","stepMatchArguments":[{"group":{"start":36,"value":"\"Doe\"","children":[{"start":37,"value":"Doe","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":33,"gherkinStepLine":27,"keywordType":"Outcome","textWithKeyword":"Then I see error message \"Error: First Name is required\"","stepMatchArguments":[{"group":{"start":20,"value":"\"Error: First Name is required\"","children":[{"start":21,"value":"Error: First Name is required","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":36,"pickleLine":29,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given I am on home page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given I Login as \"valid\"","isBg":true,"stepMatchArguments":[{"group":{"start":11,"value":"\"valid\"","children":[{"start":12,"value":"valid","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":37,"gherkinStepLine":30,"keywordType":"Context","textWithKeyword":"Given I see page containing \"Products\"","stepMatchArguments":[{"group":{"start":22,"value":"\"Products\"","children":[{"start":23,"value":"Products","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":38,"gherkinStepLine":31,"keywordType":"Action","textWithKeyword":"When I choose random item and add it to cart","stepMatchArguments":[]},{"pwStepLine":39,"gherkinStepLine":32,"keywordType":"Action","textWithKeyword":"And I open cart and verify the added item","stepMatchArguments":[]},{"pwStepLine":40,"gherkinStepLine":33,"keywordType":"Action","textWithKeyword":"And I proceed to checkout","stepMatchArguments":[]},{"pwStepLine":41,"gherkinStepLine":34,"keywordType":"Action","textWithKeyword":"When I fill checkout with only zip code \"12345\"","stepMatchArguments":[{"group":{"start":35,"value":"\"12345\"","children":[{"start":36,"value":"12345","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":42,"gherkinStepLine":35,"keywordType":"Outcome","textWithKeyword":"Then I see error message \"Error: First Name is required\"","stepMatchArguments":[{"group":{"start":20,"value":"\"Error: First Name is required\"","children":[{"start":21,"value":"Error: First Name is required","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":45,"pickleLine":37,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given I am on home page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given I Login as \"valid\"","isBg":true,"stepMatchArguments":[{"group":{"start":11,"value":"\"valid\"","children":[{"start":12,"value":"valid","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":46,"gherkinStepLine":38,"keywordType":"Context","textWithKeyword":"Given I see page containing \"Products\"","stepMatchArguments":[{"group":{"start":22,"value":"\"Products\"","children":[{"start":23,"value":"Products","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":47,"gherkinStepLine":39,"keywordType":"Action","textWithKeyword":"When I add item at index 0 to cart","stepMatchArguments":[{"group":{"start":20,"value":"0","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":48,"gherkinStepLine":40,"keywordType":"Action","textWithKeyword":"And I add item at index 1 to cart","stepMatchArguments":[{"group":{"start":20,"value":"1","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":49,"gherkinStepLine":41,"keywordType":"Action","textWithKeyword":"And I open cart and verify both items","stepMatchArguments":[]},{"pwStepLine":50,"gherkinStepLine":42,"keywordType":"Action","textWithKeyword":"And I proceed to checkout","stepMatchArguments":[]},{"pwStepLine":51,"gherkinStepLine":43,"keywordType":"Action","textWithKeyword":"And I fill checkout information with \"Jane\" \"Smith\" \"67890\"","stepMatchArguments":[{"group":{"start":33,"value":"\"Jane\"","children":[{"start":34,"value":"Jane","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":40,"value":"\"Smith\"","children":[{"start":41,"value":"Smith","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":48,"value":"\"67890\"","children":[{"start":49,"value":"67890","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":52,"gherkinStepLine":44,"keywordType":"Outcome","textWithKeyword":"Then I verify the total calculation is correct","stepMatchArguments":[]}]},
  {"pwTestLine":55,"pickleLine":46,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given I am on home page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given I Login as \"valid\"","isBg":true,"stepMatchArguments":[{"group":{"start":11,"value":"\"valid\"","children":[{"start":12,"value":"valid","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":56,"gherkinStepLine":47,"keywordType":"Context","textWithKeyword":"Given I see page containing \"Products\"","stepMatchArguments":[{"group":{"start":22,"value":"\"Products\"","children":[{"start":23,"value":"Products","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":57,"gherkinStepLine":48,"keywordType":"Action","textWithKeyword":"When I choose random item and add it to cart","stepMatchArguments":[]},{"pwStepLine":58,"gherkinStepLine":49,"keywordType":"Action","textWithKeyword":"And I open cart and verify the added item","stepMatchArguments":[]},{"pwStepLine":59,"gherkinStepLine":50,"keywordType":"Action","textWithKeyword":"And I proceed to checkout","stepMatchArguments":[]},{"pwStepLine":60,"gherkinStepLine":51,"keywordType":"Action","textWithKeyword":"And I fill checkout information with \"Test\" \"User\" \"12345\"","stepMatchArguments":[{"group":{"start":33,"value":"\"Test\"","children":[{"start":34,"value":"Test","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":40,"value":"\"User\"","children":[{"start":41,"value":"User","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":47,"value":"\"12345\"","children":[{"start":48,"value":"12345","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":61,"gherkinStepLine":52,"keywordType":"Outcome","textWithKeyword":"Then I verify checkout overview and totals","stepMatchArguments":[]}]},
  {"pwTestLine":64,"pickleLine":54,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given I am on home page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given I Login as \"valid\"","isBg":true,"stepMatchArguments":[{"group":{"start":11,"value":"\"valid\"","children":[{"start":12,"value":"valid","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":65,"gherkinStepLine":55,"keywordType":"Context","textWithKeyword":"Given I see page containing \"Products\"","stepMatchArguments":[{"group":{"start":22,"value":"\"Products\"","children":[{"start":23,"value":"Products","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":66,"gherkinStepLine":56,"keywordType":"Action","textWithKeyword":"When I choose random item and add it to cart","stepMatchArguments":[]},{"pwStepLine":67,"gherkinStepLine":57,"keywordType":"Outcome","textWithKeyword":"Then I verify cart badge shows 1","stepMatchArguments":[{"group":{"start":26,"value":"1","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":68,"gherkinStepLine":58,"keywordType":"Action","textWithKeyword":"When I choose random item and add it to cart","stepMatchArguments":[]},{"pwStepLine":69,"gherkinStepLine":59,"keywordType":"Outcome","textWithKeyword":"Then I verify cart badge shows 2","stepMatchArguments":[{"group":{"start":26,"value":"2","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":70,"gherkinStepLine":60,"keywordType":"Action","textWithKeyword":"When I open cart and verify both items","stepMatchArguments":[]},{"pwStepLine":71,"gherkinStepLine":61,"keywordType":"Action","textWithKeyword":"And I remove all items from cart","stepMatchArguments":[]},{"pwStepLine":72,"gherkinStepLine":62,"keywordType":"Outcome","textWithKeyword":"Then I verify cart badge is not visible","stepMatchArguments":[]}]},
]; // bdd-data-end